<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\libs\Tinkwell.Cli.Sdk\Tinkwell.Cli.Sdk.csproj" />
    <ProjectReference Include="..\libs\Tinkwell.Package\Tinkwell.Package.csproj" />
  </ItemGroup>

</Project>
