<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <InternalsVisibleTo Include="Tinkwell.Runlet.Actions.Tests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Google.Protobuf" />
    <PackageReference Include="Grpc.Net.Client" />
    <PackageReference Include="Grpc.Tools" PrivateAssets="All" />
    <PackageReference Include="System.IO.Ports" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\libs\Tinkwell.Actions.Abstractions\Tinkwell.Actions.Abstractions.csproj" />
    <ProjectReference Include="..\Tinkwell.Configuration.Actions\Tinkwell.Configuration.Actions.csproj" />
    <ProjectReference Include="..\Tinkwell.Events\Tinkwell.Events.csproj" />
    <ProjectReference Include="..\libs\Tinkwell.Expressions\Tinkwell.Expressions.csproj" />
    <ProjectReference Include="..\libs\Tinkwell.Runner.Abstractions\Tinkwell.Runner.Abstractions.csproj" />
    <ProjectReference Include="..\Tinkwell.Runner.Hosting\Tinkwell.Runner.Hosting.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="..\Tinkwell.Runlet.Events\Protos\events.proto"
              GrpcServices="Client" Link="Protos\events.proto" />
  </ItemGroup>

</Project>
