<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <InternalsVisibleTo Include="Tinkwell.Runlet.Signals.Tests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Google.Protobuf" />
    <PackageReference Include="Grpc.AspNetCore" />
    <PackageReference Include="Grpc.Tools" PrivateAssets="All" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Tinkwell.Events\Tinkwell.Events.csproj" />
    <ProjectReference Include="..\libs\Tinkwell.Runner.Abstractions\Tinkwell.Runner.Abstractions.csproj" />
    <ProjectReference Include="..\Tinkwell.Runner.Hosting\Tinkwell.Runner.Hosting.csproj" />
    <ProjectReference Include="..\libs\Tinkwell.Configuration.Parser\Tinkwell.Configuration.Parser.csproj" />
    <ProjectReference Include="..\libs\Tinkwell.Expressions\Tinkwell.Expressions.csproj" />
    <ProjectReference Include="..\Tinkwell.Measures\Tinkwell.Measures.csproj" />
    <ProjectReference Include="..\Tinkwell.Runlet.Measures\Tinkwell.Runlet.Measures.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="Protos\signals.proto" GrpcServices="Server" />
    <Protobuf Include="..\Tinkwell.Runlet.Events\Protos\events.proto"
              GrpcServices="Client" Link="Protos\events.proto" />
  </ItemGroup>

</Project>
