<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="Xunit.SkippableFact" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\app\libs\Tinkwell.Measures.History\Tinkwell.Measures.History.csproj" />
    <ProjectReference Include="..\..\app\Tinkwell.Measures.History.TimescaleDb\Tinkwell.Measures.History.TimescaleDb.csproj" />
  </ItemGroup>

</Project>
