<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\libs\Tinkwell.Events.Abstractions\Tinkwell.Events.Abstractions.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Tinkwell.Events.Tests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Grpc.Core.Api" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
  </ItemGroup>

  <ItemGroup>
    <None Include="README.md" />
  </ItemGroup>

</Project>
