<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\app\libs\Tinkwell.Runner.Abstractions\Tinkwell.Runner.Abstractions.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Google.Protobuf" />
    <PackageReference Include="Grpc.Net.Client" />
    <PackageReference Include="Grpc.Tools" PrivateAssets="All" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="..\..\..\src\app\Tinkwell.Runlet.Measures\Protos\measures.proto"
              GrpcServices="Client" Link="Protos\measures.proto" />
    <Protobuf Include="..\..\..\src\app\Tinkwell.Runlet.Events\Protos\events.proto"
              GrpcServices="Client" Link="Protos\events.proto" />
  </ItemGroup>

</Project>
