<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
    <Using Include="Tinkwell.Configuration" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\app\Tinkwell.Integrations\Tinkwell.Integrations.csproj" />
    <ProjectReference Include="..\..\app\libs\Tinkwell.Configuration.Abstractions\Tinkwell.Configuration.Abstractions.csproj" />
    <ProjectReference Include="..\..\app\libs\Tinkwell.Expressions\Tinkwell.Expressions.csproj" />
    <ProjectReference Include="..\..\app\libs\Tinkwell.Configuration.Parser\Tinkwell.Configuration.Parser.csproj" />
  </ItemGroup>

</Project>
