<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <InternalsVisibleTo Include="Tinkwell.Runlet.MeasureEvents.Tests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Google.Protobuf" />
    <PackageReference Include="Grpc.Net.Client" />
    <PackageReference Include="Grpc.Tools" PrivateAssets="All" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Tinkwell.Events\Tinkwell.Events.csproj" />
    <ProjectReference Include="..\Tinkwell.Measures\Tinkwell.Measures.csproj" />
    <ProjectReference Include="..\libs\Tinkwell.Runner.Abstractions\Tinkwell.Runner.Abstractions.csproj" />
    <ProjectReference Include="..\Tinkwell.Runlet.Measures\Tinkwell.Runlet.Measures.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="..\Tinkwell.Runlet.Events\Protos\events.proto"
              GrpcServices="Client" Link="Protos\events.proto" />
  </ItemGroup>

  <ItemGroup>
    <None Include="README.md" />
  </ItemGroup>

</Project>
