<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <Using Include="Tinkwell.Configuration" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Tinkwell.Runlet.TextQuery.Tests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.IO.Ports" />
    <PackageReference Include="Grpc.Net.Client" />
    <PackageReference Include="Google.Protobuf" />
    <PackageReference Include="Grpc.Tools" PrivateAssets="All" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\libs\Tinkwell.Configuration.Parser\Tinkwell.Configuration.Parser.csproj" />
    <ProjectReference Include="..\libs\Tinkwell.Runner.Abstractions\Tinkwell.Runner.Abstractions.csproj" />
    <ProjectReference Include="..\Tinkwell.Runner.Hosting\Tinkwell.Runner.Hosting.csproj" />
    <ProjectReference Include="..\libs\Tinkwell.Telemetry\Tinkwell.Telemetry.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="..\Tinkwell.Runlet.Measures\Protos\measures.proto"
              GrpcServices="Client" Link="Protos\measures.proto" />
  </ItemGroup>

</Project>
