<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <InternalsVisibleTo Include="Tinkwell.Runlet.Events.Tests" />
    <InternalsVisibleTo Include="Tinkwell.Runlet.EventPersistence" />
    <InternalsVisibleTo Include="Tinkwell.Runlet.EventPersistence.Tests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Google.Protobuf" />
    <PackageReference Include="Grpc.AspNetCore" />
    <PackageReference Include="Grpc.Tools" PrivateAssets="All" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Tinkwell.Events\Tinkwell.Events.csproj" />
    <ProjectReference Include="..\libs\Tinkwell.Runner.Abstractions\Tinkwell.Runner.Abstractions.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="Protos\events.proto" GrpcServices="Server" />
  </ItemGroup>

  <ItemGroup>
    <None Include="README.md" />
  </ItemGroup>

</Project>
