<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\libs\Tinkwell.Runner.Abstractions\Tinkwell.Runner.Abstractions.csproj" />
    <ProjectReference Include="..\Tinkwell.Runlet.Store\Tinkwell.Runlet.Store.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Grpc.AspNetCore" />
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="Protos\store_replication.proto" GrpcServices="Both" />
  </ItemGroup>

  <ItemGroup>
    <None Include="README.md" />
  </ItemGroup>

</Project>
