<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\app\libs\Tinkwell.Runner.Abstractions\Tinkwell.Runner.Abstractions.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Google.Protobuf" />
    <PackageReference Include="Grpc.AspNetCore" />
    <PackageReference Include="Grpc.Tools" PrivateAssets="All" />
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="Protos\measure_reader.proto" GrpcServices="Server" />
    <Protobuf Include="..\..\..\src\app\Tinkwell.Runlet.Measures\Protos\measures.proto"
              GrpcServices="Client" Link="Protos\measures.proto" />
  </ItemGroup>

</Project>
