using System.Globalization;

namespace Tinkwell.Package;

/// <summary>
/// Parses and writes <c>security/signatures.tw</c> files.
/// </summary>
internal static class SignaturesFormat
{
    /// <summary>Parses a <c>signatures.tw</c> file from its text content.</summary>
    /// <param name="text">Full content of the <c>signatures.tw</c> file (a <c>signatures</c> block with <c>file</c> children).</param>
    public static PackageSignatures Parse(string text)
    {
        var block = TwReader.ReadSingleBlock(text);

        if (!block.Type.Equals("signatures", StringComparison.OrdinalIgnoreCase))
            throw new PackageException(
                $"Expected 'signatures' block, found '{block.Type}'");

        var algorithm = block.Name;
        if (string.IsNullOrWhiteSpace(algorithm))
            throw new PackageException("Signatures algorithm is required");

        var files = new List<FileSignature>();
        foreach (var child in block.Children)
        {
            if (!child.Type.Equals("file", StringComparison.OrdinalIgnoreCase))
                throw new PackageException(
                    $"Expected 'file' block inside signatures, found '{child.Type}'");

            if (string.IsNullOrWhiteSpace(child.Name))
                throw new PackageException("File path is required in signatures");

            if (!child.Properties.TryGetValue("hash", out var hash) ||
                string.IsNullOrWhiteSpace(hash))
                throw new PackageException($"Missing hash for file '{child.Name}'");

            if (!child.Properties.TryGetValue("size", out var sizeStr) ||
                !long.TryParse(sizeStr, NumberStyles.Integer, CultureInfo.InvariantCulture, out var size))
                throw new PackageException($"Missing or invalid size for file '{child.Name}'");

            files.Add(new FileSignature
            {
                Path = child.Name,
                Hash = hash,
                Size = size,
            });
        }

        return new PackageSignatures
        {
            Algorithm = algorithm,
            Files = files,
        };
    }

    /// <summary>Serializes <paramref name="signatures"/> to canonical <c>signatures.tw</c> text format.</summary>
    /// <param name="signatures">Package signatures to serialize, including the algorithm label and per-file hashes.</param>
    public static string Write(PackageSignatures signatures)
    {
        var children = signatures.Files
            .Select(f => new TwBlock("file", f.Path, new Dictionary<string, string>
            {
                ["hash"] = f.Hash,
                ["size"] = f.Size.ToString(CultureInfo.InvariantCulture),
            }, []))
            .ToList();

        var block = new TwBlock("signatures", signatures.Algorithm,
            new Dictionary<string, string>(), children);

        return "# Auto-generated by Tinkwell.Package -- do not edit\n" +
            TwWriter.Write(block);
    }
}
