<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.Data.Sqlite" />
    <PackageReference Include="Microsoft.Extensions.Configuration" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\app\Tinkwell.Runlet.EventPersistence\Tinkwell.Runlet.EventPersistence.csproj" />
    <ProjectReference Include="..\..\app\Tinkwell.Runlet.Events\Tinkwell.Runlet.Events.csproj" />
    <ProjectReference Include="..\..\app\Tinkwell.Events\Tinkwell.Events.csproj" />
  </ItemGroup>

</Project>
