<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="UnitsNet" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\libs\Tinkwell.Core\Tinkwell.Core.csproj" />
    <ProjectReference Include="..\libs\Tinkwell.Expressions\Tinkwell.Expressions.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="README.md" />
  </ItemGroup>

</Project>
