namespace Tinkwell.Measures;

/// <summary>
/// Event data raised when a measure's value changes.
/// </summary>
public sealed class ValueChangedEventArgs : EventArgs
{
    public required string Name { get; init; }
    public required MeasureValue OldValue { get; init; }
    public required MeasureValue NewValue { get; init; }

    /// <summary>
    /// Tracks causal chains (e.g. a source measure change cascading through
    /// derived measures and triggering signals). When <see langword="null"/>
    /// one is generated by the registry on update.
    /// </summary>
    public string? CorrelationId { get; init; }
}
