name: Build and Test (PR)

on:
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches: [ "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13.5'

    - name: Build solution
      run: |
        dotnet restore Source/Tinkwell.sln
        dotnet build Source/Tinkwell.sln --configuration Release --no-restore

    - name: Run unit tests
      run: dotnet test Source/Tinkwell.sln --no-build --configuration Release --verbosity normal --filter Category!=CI-Disabled

    - name: Publish application
      run: |
        mkdir ./app
        for proj in $(find ./Source -name "*.csproj" | grep -v -i "Tests/"); do
          echo "Publishing $proj..."
          dotnet publish "$proj" -c Release -o "./app"
        done

    - name: Run integration tests
      run: python Source/Tests/Integration/run_tests.py --app-path ./app --trait integration --verbose
