name: Release and bump version

on:
  release:
    types: [published]

jobs:
  build-publish-zip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore Source/Tinkwell.sln

      - name: Build solution
        run: dotnet build Source/Tinkwell.sln --configuration Release --no-restore

      - name: Create output directory
        run: mkdir ./app

      - name: Publish application
        run: |
          for proj in $(find ./Source -name "*.csproj" | grep -v -i "Tests/"); do
            echo "Publishing $proj..."
            dotnet publish "$proj" -c Release -o "./app"
          done

      - name: Archive published output
        run: |
          cd app
          zip -r ../tinkwell-${{ github.event.release.tag_name }}.zip .

      - name: Attach ZIP artifact to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: tinkwell-${{ github.event.release.tag_name }}.zip
          asset_name: tinkwell-${{ github.event.release.tag_name }}.zip
          asset_content_type: application/zip          

  bump-version:
    needs: build-publish-zip
    runs-on: ubuntu-latest

    steps:
      - name: Checkout with full history
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Bump version
        id: bump
        uses: vers-one/dotnet-project-version-updater@v1.7
        with:
          file: 'Source/Directory.Build.Props'
          version: bump-patch
          tags: props.Version, props.AssemblyVersion, props.FileVersion, props.InformationalVersion

      - name: Commit and push version bump
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add Source/Directory.Build.Props
          git commit -m "chore: bump version to ${{ steps.bump.outputs.newVersion }}"
          git push
          
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: bump version to ${{ steps.bump.outputs.newVersion }} [skip ci]'
          title: 'chore: bump version to ${{ steps.bump.outputs.newVersion }}'
          body: |
            This PR was created automatically by GitHub Actions to bump the 
            project version to **${{ steps.bump.outputs.newVersion }}**.
          head: bump-version-${{ steps.bump.outputs.newVersion }}
          base: master
          labels: autogenerated, auto-merge
          auto-merge: true
          merge-method: squash