name: Release and bump version

permissions:
  contents: write
  pull-requests: write

on:
  release:
    types: [published]

jobs:
  build-publish-zip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13.5'

      - name: Build solution
        run: |
          dotnet restore Source/Tinkwell.sln
          dotnet build Source/Tinkwell.sln --configuration Release --no-restore

      - name: Publish application
        run: |
          mkdir ./app
          for proj in $(find ./Source -name "*.csproj" | grep -v -i "Tests/"); do
            echo "Publishing $proj..."
            dotnet publish "$proj" -c Release -o "./app"
          done

      - name: Run smoke tests
        run: python Source/Tests/Integration/run_tests.py --app-path ./app --trait smoke --verbose

      - name: Archive published output
        run: |
          cd app
          zip -r ../tinkwell-${{ github.event.release.tag_name }}.zip .

      - name: Attach ZIP artifact to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: tinkwell-${{ github.event.release.tag_name }}.zip
          asset_name: tinkwell-${{ github.event.release.tag_name }}.zip
          asset_content_type: application/zip          

  bump-version:
    needs: build-publish-zip
    runs-on: ubuntu-latest

    steps:
      - name: Checkout with full history
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Bump version
        id: bump
        uses: vers-one/dotnet-project-version-updater@v1.7
        with:
          file: 'Source/Directory.Build.Props'
          version: bump-revision
          tags: props.Version, props.AssemblyVersion, props.FileVersion, props.InformationalVersion

      - name: Commit and push version bump
        run: |
          git checkout -b bump-version-${{ steps.bump.outputs.newVersion }}
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add Source/Directory.Build.Props
          git commit -m "chore: bump version to ${{ steps.bump.outputs.newVersion }}"
          git push origin HEAD --set-upstream
          
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'Bump version to ${{ steps.bump.outputs.newVersion }}'
          branch: example-patches
          delete-branch: true
          title: '[skip ci] Bump version to ${{ steps.bump.outputs.newVersion }}'
          body: |
            Version bumped to ${{ steps.bump.outputs.newVersion }} because
            ${{ github.event.release.tag_name }} has been released.
          labels: automated
          merge-method: squash
          auto-merge: true